apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pullrequest
spec:
  params:
  - name: URL
    value: $(body.repository.url)
  - name: REVISION
    value: $(body.head_commit.id)
